print('Укажите имя кота или кошки 1: ')
catName1 = input()
print('Укажите имя кота или кошки 2: ')
catName2 = input()
print('Укажите имя кота или кошки 3: ')
catName3 = input()
print('Укажите имя кота или кошки 4: ')
catName4 = input()
print('Укажите имя кота или кошки 5: ')
catName5 = input()
print('Укажите имя кота или кошки 6: ')
catName6 = input()

print(catName1 + ' ' + catName2 + ' ' + catName3 + ' ' + catName4 + ' ' + catName5 + ' ' + catName6)